effect: BLIND
duration: 999999
amplifier: 4

# VALID EFFECTS:
  #ABSORPTION
  #BAD_OMEN
  #BLINDNESS
  #CONFUSION
  #DAMAGE_RESISTANCE
  #DOLPHINS_GRACE
  #FAST_DIGGING
  #FIRE_RESISTANCE
  #GLOWING
  #HEAL
  #HEALTH_BOOST
  #HERO_OF_THE_VILLAGE
  #HUNGER
  #INCREASE_DAMAGE
  #INVISIBILITY
  #JUMP
  #LEVITATION
  #LUCK
  #NIGHT_VISION
  #POISON
  #REGENERATION
  #SATURATION
  #SLOW
  #SLOW_DIGGING
  #SLOW_FALLING
  #SPEED
  #UNLUCK
  #WATER_BREATHING
  #WEAKNESS
  #WITHER